### ISSUE TITLE
About diffusion coefficient

### ISSUE THREAD

**Issue by Yong-Q** [Xinbingru/COFsMembraneML#1]
Surprisingly, it is found that the diffusion coefficient can be predicted very well by the structural coefficients such as the aperture, and other characteristics seem to be not so important, which does not seem to be very consistent with previous studies. Machine learning algorithms are also commonly used classical algorithms.

**Comment by Xinbingru** [comment]
In fact, the diffusion coefficient is less accurate than the adsorption properties, but we chose the ML model with relatively high accuracy to calculate the SHAP values of the features. If you only use structural features such as pore size to predict the diffusion coefficient, you will get much lower accuracy and correspondingly less reliable SHAP values.

**Comment by Yong-Q** [comment]
Ok, I will replicate this work in other data sets as soon as possible

**Comment by Xinbingru** [comment]
No problem at all. Feel free to talk to me if you have any questions. Of course, it would be great if you could cite my work : )

**Comment by Yong-Q** [comment]
If possible, can you share a batch processing script to get the required features? This may greatly improve the speed at which others replicate the work. thank you！

**Comment by Yong-Q** [comment]
This may not include the calculation of the diffusion coefficient or the calculation of adsorption selectivity, although it would be better if both were included.

**Comment by Xinbingru** [comment]
> If possible, can you share a batch processing script to get the required features? This may greatly improve the speed at which others replicate the work. thank you！

In fact, you can find the algorithms for each descriptor in my paper's supporting information.In addition, you can also find some scripts on Github for information extraction of CIF files, I hope this will help you.
